#!/bin/bash
export PATH=/usr/sbin:/usr/bin
# 加载必要驱动，注意顺序
insmod /lib/modules/3.10.0-1160.el7.x86_64/kernel/drivers/message/fusion/mptbase.ko.xz
insmod /lib/modules/3.10.0-1160.el7.x86_64/kernel/drivers/message/fusion/mptscsih.ko.xz
insmod /lib/modules/3.10.0-1160.el7.x86_64/kernel/drivers/scsi/scsi_transport_spi.ko.xz
insmod /lib/modules/3.10.0-1160.el7.x86_64/kernel/drivers/message/fusion/mptspi.ko.xz
/bin/bash
